# Generated by Django 4.2.4 on 2023-08-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя пользователя', max_length=200, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.account', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Укажите месяц', max_length=200, verbose_name='Месяц')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя сервиса', max_length=200, verbose_name='Имя сервиса')),
            ],
            options={
                'verbose_name': ('Сервис',),
                'verbose_name_plural': 'Сервисы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость квитанции')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.account', verbose_name='Клиент')),
                ('period_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.period', verbose_name='Период')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость сервиса')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_dets', to='bill.bill', verbose_name='Квитанция')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.service', verbose_name='Сервис')),
            ],
            options={
                'ordering': ['bill_id'],
            },
        ),
        migrations.CreateModel(
            name='Bill_adj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость квитанции')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.account', verbose_name='Клиент')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_adj', to='bill.bill', verbose_name='Квитанция')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.service', verbose_name='Сервис')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='period_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.period', verbose_name='Период'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость квитанции')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.account', verbose_name='Клиент')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='bill.bill', verbose_name='Квитанция')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.service', verbose_name='Сервис')),
            ],
        ),
    ]
